# Generated by Django 4.1.7 on 2023-03-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("type_speed", "0002_scores_customtext"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(default="Other", max_length=32),
        ),
        migrations.AlterField(
            model_name="scores",
            name="accuracy",
            field=models.CharField(max_length=32),
        ),
    ]
