# Generated by Django 4.1.7 on 2023-03-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("type_speed", "0003_user_gender_alter_scores_accuracy"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="title",
            field=models.CharField(default="Blank", max_length=64),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(default="other", max_length=32),
        ),
    ]
