# Generated by Django 4.1.7 on 2023-03-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("type_speed", "0004_customtext_title_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="scores",
            name="custom",
            field=models.BooleanField(default=False),
        ),
    ]
