# Generated by Django 4.1.7 on 2023-03-08 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_post_people_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="people_like",
        ),
        migrations.AddField(
            model_name="post",
            name="people_like",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="liked_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
