# Generated by Django 4.1.7 on 2023-02-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_bid_comments_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(),
        ),
    ]
