# Generated by Django 4.1.7 on 2023-02-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_listing_in_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="in_watchlist",
            field=models.BooleanField(default=True),
        ),
    ]
