# Generated by Django 4.1.7 on 2023-02-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_alter_listing_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="bid",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
            preserve_default=False,
        ),
    ]
