# Generated by Django 4.1.7 on 2023-02-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_rename_bid_bid_amount_bid_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="listing",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="creator",
            field=models.CharField(default=True, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comments",
            name="comment",
            field=models.CharField(max_length=1000),
        ),
    ]
