# Generated by Django 4.1.7 on 2023-02-28 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0016_remove_listing_winner_alter_listing_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="creator",
        ),
    ]
